### ISSUE TITLE
I use npm install，ReferenceError: require is not defined

### ISSUE THREAD

**Issue by Gordon-007** [baimingxuan/react-admin-design#1]
node 18 + npm 8.15.0
npm install
npm run dev

it run with error:
ReferenceError: require is not defined
    at cleanRequireCache (file:///D:/webstormSpace/com.react/react-admin-design/node_modules/vite-plugin-mock/dist/index.mjs:128:3)
    at getMockConfig (file:///D:/webstormSpace/com.react/react-admin-design/node_modules/vite-plugin-mock/dist/index.mjs:157:3)
    at createMockServer (file:///D:/webstormSpace/com.react/react-admin-design/node_modules/vite-plugin-mock/dist/index.mjs:52:20)
    at configResolved (file:///D:/webstormSpace/com.react/react-admin-design/node_modules/vite-plugin-mock/dist/index.mjs:246:16)
    at file:///D:/webstormSpace/com.react/react-admin-design/node_modules/vite/dist/node/chunks/dep-ErEj4WmL.js:66034:24
    at Array.map (<anonymous>)
    at resolveConfig (file:///D:/webstormSpace/com.react/react-admin-design/node_modules/vite/dist/node/chunks/dep-ErEj4WmL.js:66034:10)
    at async _createServer (file:///D:/webstormSpace/com.react/react-admin-design/node_modules/vite/dist/node/chunks/dep-ErEj4WmL.js:58335:20)
    at async CAC.<anonymous> (file:///D:/webstormSpace/com.react/react-admin-design/node_modules/vite/dist/node/cli.js:764:24)

**Comment by Gordon-007** [comment]
when vite-plugin-mock version down to 2.9.8，it run well

**Comment by baimingxuan** [comment]
yes，you are right, thank you

**Comment by baimingxuan** [comment]
It's been fixed

**Comment by condorheroblog** [comment]
@baimingxuan Are you interested in using [vite-plugin-fake-server](https://github.com/condorheroblog/vite-plugin-fake-server) to replace `vite-plugin-mock`.
